// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlI1qgsjotY9YBrEH2mbojHvBlBAvSRqA',
    appId: '1:139550162253:web:dec0b1c3e55a3f812bcb04',
    messagingSenderId: '139550162253',
    projectId: 'ganesh-chanda-9cf2a',
    authDomain: 'ganesh-chanda-9cf2a.firebaseapp.com',
    storageBucket: 'ganesh-chanda-9cf2a.firebasestorage.app',
    measurementId: 'G-33FXVYTS73',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhcTDaRXNBxYkAcDw9Dmu89Uf-zp7HMWY',
    appId: '1:139550162253:android:d9980efbdcd882342bcb04',
    messagingSenderId: '139550162253',
    projectId: 'ganesh-chanda-9cf2a',
    storageBucket: 'ganesh-chanda-9cf2a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFqJx0EWsoNT-LNlZU9Y0fJJ_obXgCBes',
    appId: '1:139550162253:ios:6278ae0aaf95d9282bcb04',
    messagingSenderId: '139550162253',
    projectId: 'ganesh-chanda-9cf2a',
    storageBucket: 'ganesh-chanda-9cf2a.firebasestorage.app',
    iosClientId: '139550162253-h389msqq2347o4a4d3kjm066nf2idrr0.apps.googleusercontent.com',
    iosBundleId: 'com.pk.ganeshChanda',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFqJx0EWsoNT-LNlZU9Y0fJJ_obXgCBes',
    appId: '1:139550162253:ios:6278ae0aaf95d9282bcb04',
    messagingSenderId: '139550162253',
    projectId: 'ganesh-chanda-9cf2a',
    storageBucket: 'ganesh-chanda-9cf2a.firebasestorage.app',
    iosClientId: '139550162253-h389msqq2347o4a4d3kjm066nf2idrr0.apps.googleusercontent.com',
    iosBundleId: 'com.pk.ganeshChanda',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlI1qgsjotY9YBrEH2mbojHvBlBAvSRqA',
    appId: '1:139550162253:web:0044c1f5390fdf852bcb04',
    messagingSenderId: '139550162253',
    projectId: 'ganesh-chanda-9cf2a',
    authDomain: 'ganesh-chanda-9cf2a.firebaseapp.com',
    storageBucket: 'ganesh-chanda-9cf2a.firebasestorage.app',
    measurementId: 'G-XPMXV8MFLP',
  );
}
